Repository soumita1234/HelpingHand, pull requests merged in 2021-06, with the labels that each got.

#27 ReadMe.md file
  README.md
  images/HelpingHand-1.JPG
  images/HelpingHand-2.JPG
  images/HelpingHand.JPG
  images/profile.jfif
Labels: LGMSOC21, 🟨 Level2

#26 Update README.md
  README.md
Labels: LGMSOC21, 🟨 Level2

#30 Added scroll to top button
  index.html
Labels: 🟩 Level1

#32 Update README.md
  README.md
Labels: LGMSOC21, 🟪 Level0

#38 Changes to Navbar
  style.css
Labels: 🟪 Level0

#44 Image Hover Effect Added
  images/child-color.jpg
  index.html
  style.css
Labels: 🟩 Level1

#45 Changed the styles of the footer
  style.css
Labels: LGMSOC21, 🟪 Level0

#50 code of conduct
  CODE_OF_CONDUCT.md
Labels: LGMSOC21, 🟪 Level0

#51 Issue #46 | Added JQuery and smooth scroll
  index.html
Labels: LGMSOC21, 🟩 Level1

#56 Changed Copyright Year
  index.html
Labels: LGMSOC21, 🟪 Level0

#58 Added flip card animation
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#66 Redesign the Mission Section
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#70 Updated Donate here button UI design #60
  style.css
Labels: LGMSOC21, 🟩 Level1

#71 Added a logo design for HelpingHand #54
  images/logo.png
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#72 FAQ section added with some general question answers.
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#74 Updated Readme.md
  README.md
Labels: LGMSOC21, 🟪 Level0

#75 Issue #57 | Responsive header for small devices | Updated style.css
  style.css
Labels: LGMSOC21, 🟩 Level1

#86 Improved FAQ Section
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#85 Add issue #48 to main
  style.css
Labels: LGMSOC21, 🟩 Level1

#78 Contributing Guidelines.md file added
  CONTRIBUTING_GUIDELINES.md
  images/contributing_guidelines.png
Labels: LGMSOC21, 🟪 Level0

#94 New feature added to the FAQ section #93
  style.css
Labels: LGMSOC21, 🟪 Level0

#96 README.md updated
  README.md
Labels: LGMSOC21, 🟪 Level0

#109 Social media links now open in new tab on clicking
  index.html
Labels: LGMSOC21, 🟪 Level0

#107 Added contact section and Updated new feature to the Footer section
  images/contact_illustration.png
  images/support-logo_footer.png
  index.html
  style.css
Labels: LGMSOC21, 🟧 Level3

#118 Updated the area of every section and fixed the footer issue , issue#106
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#120 Footer updated
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#110 Adding FAQ Improvement (#100)
  README.md
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#130 Added responsiveness to features section and footer
  index.html
  style.css
Labels: LGMSOC21, 🟪 Level0

#131 Updated the style of the child image
  images/child2.jpg
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#135 Updated Footer and Contributing Guidelines
  CONTRIBUTING_GUIDELINES.md
  index.html
  style.css
Labels: LGMSOC21, 🟪 Level0

#140 Updated Bug:Navbar and FAQ section
  images/HelpingHand-1.JPG
  images/HelpingHand-2.JPG
  images/HelpingHand.JPG
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#144 Updated Mission section and Footer ; issue #138
  images/Card-1.png
  images/Card-2.jpg
  images/Card-3.jpg
  index.html
Labels: LGMSOC21, 🟪 Level0

#150 Updated file changes
  app.js
  images/profile.jfif
  index.html
  style.css
Labels: LGMSOC21, 🟩 Level1

#153 Resolved issue #145
  app.js
  index.html
Labels: LGMSOC21, 🟪 Level0

#158 Isuue #156 resolved
  style.css
Labels: LGMSOC21, 🟪 Level0
